export const runStartStep = async () => {
  try {
  } catch (error) {
    console.error("Error running start step:", error)
    throw error
  }
}
